gazebo_ros_control:
  pid_gains:
    neck_y_joint: {p: 100.0, i: 0.01, d: 10.0}
    neck_p_joint: {p: 100.0, i: 0.01, d: 10.0}
    neck_r_joint: {p: 100.0, i: 0.01, d: 10.0}

    waist_y_joint: {p: 100.0, i: 0.01, d: 10.0}
    waist_p_joint: {p: 100.0, i: 0.01, d: 10.0}
    waist_r_joint: {p: 100.0, i: 0.01, d: 10.0}

    r_shoulder_p_joint: {p: 100.0, i: 0.01, d: 10.0}
    r_shoulder_r_joint: {p: 100.0, i: 0.01, d: 10.0}
    r_shoulder_y_joint: {p: 100.0, i: 0.01, d: 10.0}
    r_elbow_joint:      {p: 100.0, i: 0.01, d: 10.0}
    r_wrist_y_joint:    {p: 100.0, i: 0.01, d: 10.0}
    r_wrist_p_joint:    {p: 100.0, i: 0.01, d: 10.0}
    r_wrist_r_joint:    {p: 100.0, i: 0.01, d: 10.0}

    l_shoulder_p_joint: {p: 100.0, i: 0.01, d: 10.0}
    l_shoulder_r_joint: {p: 100.0, i: 0.01, d: 10.0}
    l_shoulder_y_joint: {p: 100.0, i: 0.01, d: 10.0}
    l_elbow_joint:      {p: 100.0, i: 0.01, d: 10.0}
    l_wrist_y_joint:    {p: 100.0, i: 0.01, d: 10.0}
    l_wrist_p_joint:    {p: 100.0, i: 0.01, d: 10.0}
    l_wrist_r_joint:    {p: 100.0, i: 0.01, d: 10.0}

    knee_joint:  {p: 100.0, i: 0.01, d: 10.0}
    ankle_joint: {p: 100.0, i: 0.01, d: 10.0}

    l_thumb_joint:     {p: 100.0, i: 0.01, d: 10.0}
    l_indexbase_joint: {p: 100.0, i: 0.01, d: 10.0}
    l_indexmid_joint:  {p: 100.0, i: 0.01, d: 10.0}
    l_indexend_joint:  {p: 100.0, i: 0.01, d: 10.0}

    r_thumb_joint:     {p: 100.0, i: 0.01, d: 10.0}
    r_indexbase_joint: {p: 100.0, i: 0.01, d: 10.0}
    r_indexmid_joint:  {p: 100.0, i: 0.01, d: 10.0}
    r_indexend_joint:  {p: 100.0, i: 0.01, d: 10.0}
